# Hydrodynamic Model Setup


## Study site description


## TUFLOWFV 3D Hydrodynamic Model

The hydrodynamic modelling component of these assessments was undertaken using TUFLOW FV, which is developed and distributed by BMT. TUFLOW FV is a numerical hydrodynamic model that solves the two-dimensional (2D) and three-dimensional (3D) Non-Linear Shallow Water Equations (NLSWE) (BMT, 2019). The model is suitable for simulating a wide range of hydrodynamic systems ranging in scale from open channels and floodplains, through estuaries to coasts and oceans. The three-dimensional model was deployed in this study.
The Finite-Volume (FV) numerical scheme employed by TUFLOW FV solves the NLSWE on both structured rectilinear grids and unstructured meshes comprised of triangular and quadrilateral elements. The flexible mesh allows for seamless boundary fitting along complex coastlines or channels as well as accurately and efficiently representing complex bathymetries with a minimum number of computational elements. The flexible mesh capability is particularly efficient at resolving a range of scales in a single model without requiring multiple domain nesting.
TUFLOW FV simulated the fate and transport of dissolved quantities, salt, temperature and all water quality constituents using the Advection Dispersion (AD) module (Figure 3.1). The AD module determines the movement of quantities that relate to density and hence vertical (density driven) stratification, and the higher order scheme implemented by TUFLOW FV resolves and maintains these gradients. The AD module supports the use of tracers to undertake flushing studies such as in the case of the Mina Palace Flushing study.



## Model domain


### Model mesh 


### Bathymetry

## Boundary conditions

### Metrological data

### Tidal data

### Open ocean boundary data

### Wave data

### Inflow and discharge data




