# \textcolor{blue}{Hydrodynamic Model}

## TUFLOFV 3D Hydrodynamic Model

The hydrodynamic modelling was undertaken using the [TUFLOW FV](https://www.tuflow.com/products/tuflow-fv/) software, which is developed and distributed by [BMT](https://www.bmt.org/). TUFLOW FV is a numerical hydrodynamic model solving the two-dimensional (2D) and three-dimensional (3D) Non-Linear Shallow Water Equations (NLSWE). The model is suitable for simulating a wide range of hydrodynamic systems ranging in scale from open channels and floodplains, through estuaries to coasts and deep offshore. The three-dimensional model was deployed in this study.

The Finite-Volume (FV) numerical scheme employed by TUFLOW FV solves the NLSWE on unstructured meshes comprised of triangular and quadrilateral elements. The flexible mesh allows for seamless boundary fitting along complex coastlines or channels as well as accurately and efficiently representing complex bathymetries with a minimum number of computational elements. The flexible mesh capability is particularly efficient at resolving a range of scales in a single model without requiring multiple domain nesting. In the present study, a flexible mesh of triangular elements with varying spatial resolution has been employed. Furthermore, the models developed by BMT incorporate a hybrid (fixed z-sigma) coordinate scheme. 

TUFLOW FV provides various options to vertically average 3D output and thereby simplify post-processing tasks. Both
MATLAB and Python visualisation libraries are available for download on the TUFLOW website to assist with review and presentation of 3D results. Further details regarding the numerical scheme employed by TUFLOW FV are provided in the [TUFLOW FV Science Manual](https://downloads.tuflow.com/_archive/TUFLOW_FV/Manual/TUFLOW_FV_User_Manual_2020.pdf).



## Model domain, mesh and bathymetry 


The hydrodynamic model domain is shown in Figure 4-1 and extends from Mandurah in the south to Quinns Rock (10 km North of JoondaluP) in the north, covering approximately 400 km of coastline. Offshore the model extends approximately 140 km into the Indian Ocean to depths greater than 4 000 m.
The model consists of 16 014 horizontal mesh cells with dimensions varying from approximately 9.0 km at the offshore boundary, and decreasing to 50 m in the vicinity of the PSDP (and proposed future) outfall diffuser. Figure 4-2 shows a detail of the model mesh in the study area.
A 10 m digital elevation model (DEM) was generated for the study area from a range of data sources (Table 4-1). In particular, the DEM was supplemented with finer resolution multibeam data over the Australian Marine Complex (AMC), Exit, Parmelia, Success, Calista and Stirling channels provided by Fremantle Ports Authority (FPA). Data from Geosciences Australia and General Bathymetric Chart of the Oceans (GEBCO) were used to complement the bathymetric information


### Bathymetry

## Boundary conditions

### Metrological data

### Tidal data

### Open ocean boundary data

### Wave data

### Inflow and discharge data


# Model Calibration


## Data Sourcing


### ADCP data 

### Currents


### Waves


### Tempearure and Salinity

## Model validation

